### ISSUE TITLE
Link to technical articles in blog password protected

### ISSUE THREAD

**Issue by justinwiley** [s-macke/starflight-reverse#1]
Congrats on the cool project, I spent many fond hours being lost in Starflight.

I noticed the link in "Take a look at the technical articles" leads to a password protected site.  Not sure if that is intentional?

Also, a translation to javascript (a forth derived language) would be great as well. ;)

**Comment by s-macke** [comment]
Unfortunately most of the information can no longer be found on the internet. Hence I created a small webarchive here: https://github.com/s-macke/starflight-reverse/tree/master/webarchive

Right now I don't plan to translate it into JavaScript. But I don't think this will be problem. C and JavaScript are very close. But I have planned something else in JavaScript.

Have fun and stay tuned.
