### ISSUE TITLE
Forth sources

### ISSUE THREAD

**Issue by oco2000** [s-macke/starflight-reverse#2]
Hello
You did a great job!

Do you know that Forth sources are available?
See [here](http://www.oocities.org/timessquare/maze/4979/lee.html)
[Zipped](http://www.oocities.org/timessquare/maze/4979/SFFiles.zip)

**Comment by s-macke** [comment]
Yes, I know. I referenced them in the folder [webarchive](https://github.com/s-macke/starflight-reverse/tree/master/webarchive) together with other Forth sources. However, they are both incomplete and don't represent the final version. 

But thanks for the reference. I have corrected the link to the document in the read me.

**Comment by oco2000** [comment]
Oh, I seemed to miss that

**Comment by oco2000** [comment]
Yes, I can see only the kernel sources there
The most interesting parts are missing (see dir.txt file)

**Comment by s-macke** [comment]
I wish someone would have an complete copy of the website http://www.sonic.net/~sage/sf from Tim Lee. The web archive has only an incomplete copy.
